Add Kate's Super Easy Spag Bol recipe.
compsoc-edinburgh/cook-book pull request #22
Opened 2022-07-06 22:30 UTC by kate-shen

2022-07-06 22:55 UTC, neanias reviewed
Looks good! Left a few editorial notes to make it a bit clearer/easier to understand for first time cooks

2022-07-06 22:55 UTC, neanias commented on main_courses/0-easy/kates_super_easy_spag_bol.md
> +4. Make up around 400ml of stock with the stock cube, then add to the pan.
```suggestion
4. Dissolve the stock cube in around 400ml of hot water, then add to the pan.
```

2022-07-06 22:55 UTC, neanias commented on main_courses/0-easy/kates_super_easy_spag_bol.md
> +6. Simmer for around 45 minutes or until thick. Make sure the temperature is consistent and it won't boil over for the first while; thereafter you don't need to pay particularly close attention to it
```suggestion
6. Simmer for around 45 minutes or until thick. Keep it at a medium heat, stirring occasionally. It shouldn't boil over, so you can leave it be.
```

2022-08-04 16:09 UTC, kate-shen commented
oops - this should probably have gone in another pull request but I'm not quite sure how this happened

2022-08-10 14:58 UTC, neanias requested changes
One more edit, then happy to merge!

2022-08-10 14:58 UTC, neanias commented on desserts/0-easy/kates_super_easy_chocolate_cheesecake.md
> +7. Decrease the heat to a low heat, and break the chocolate into small pieces and melt in the bowl when ready.
```suggestion
7. Once boiling, decrease the heat to a low heat, and break the chocolate into small pieces and melt in the bowl. 
```

2022-08-10 23:32 UTC, kate-shen commented
Should have made the change now, not sure why it's not picking up on the change

2022-08-11 08:11 UTC, neanias approved these changes

2022-08-21 16:12 UTC, yutotakano commented
Sounds good to merge then :)

2022-08-21 16:12 UTC, merged